export type Feature = { title: string; description: string };
export type Spec = { label: string; value: string };
export type Vehicle = {
  id?: string;
  slug: string;
  title: string;
  subtitle: string;
  intro: string;
  price: string;
  availability: string;
  hero_image: string;
  gallery: string[];
  features: Feature[];
  specs: Spec[];
  featured: boolean;
};

export const fallbackVehicles: Vehicle[] = [
  {slug:'tiguan',title:'Nova Tiguan',subtitle:'Tecnologia, espaço e performance para ir além.',intro:'A nova Tiguan combina presença, sofisticação e tecnologia em um SUV desenvolvido para quem espera mais.',price:'',availability:'',hero_image:'',gallery:[],features:[['4Motion','Tração integral para mais confiança em diferentes condições.'],['350 TSI','Performance e resposta para uma condução envolvente.'],['15 polegadas','Multimídia ampla e conectada.'],['Assistência','Tecnologias que ajudam a tornar cada viagem mais confortável.']].map(([title,description])=>({title,description})),specs:[['Motor','2.0 350 TSI'],['Potência','272 cv'],['Transmissão','Automática de 8 velocidades'],['Tração','4Motion']].map(([label,value])=>({label,value})),featured:true},
  {slug:'taos',title:'Taos',subtitle:'Mais espaço para viver cada momento.',intro:'Um SUV equilibrado para quem valoriza espaço, conforto, tecnologia e a experiência Volkswagen.',price:'',availability:'',hero_image:'',gallery:[],features:[['Espaço interno','Conforto para passageiros e versatilidade para a rotina.'],['Tecnologia','Conectividade e recursos pensados para facilitar seu dia.'],['Conforto','Uma cabine desenvolvida para viagens mais agradáveis.'],['Design','Linhas marcantes e presença de SUV.']].map(([title,description])=>({title,description})),specs:[['Categoria','SUV'],['Motorização','Turbo'],['Transmissão','Automática'],['Capacidade','5 ocupantes']].map(([label,value])=>({label,value})),featured:true},
  {slug:'t-cross',title:'T-Cross',subtitle:'Compacto por fora. Completo por dentro.',intro:'O SUV Volkswagen que combina versatilidade, segurança, tecnologia e praticidade para a cidade.',price:'',availability:'',hero_image:'',gallery:[],features:[['Versatilidade','Dimensões que facilitam a rotina sem abrir mão do espaço.'],['Segurança','Recursos de assistência e proteção para seus trajetos.'],['Tecnologia','Conectividade para deixar tudo mais simples.'],['Design','Personalidade forte e assinatura Volkswagen.']].map(([title,description])=>({title,description})),specs:[['Categoria','SUV compacto'],['Motorização','Turbo'],['Transmissão','Automática'],['Ocupantes','5']].map(([label,value])=>({label,value})),featured:true},
  {slug:'nivus',title:'Nivus',subtitle:'Design que chama atenção. Tecnologia que acompanha.',intro:'Um crossover Volkswagen com visual marcante, conectividade e uma condução que combina com a cidade.',price:'',availability:'',hero_image:'',gallery:[],features:[['Design fastback','Silhueta esportiva e identidade marcante.'],['Tecnologia','Recursos digitais para uma experiência conectada.'],['Conforto','Interior pensado para o uso diário.'],['Eficiência','Conjunto equilibrado para diferentes trajetos.']].map(([title,description])=>({title,description})),specs:[['Categoria','Crossover'],['Motor','Turbo 200 TSI'],['Transmissão','Automática'],['Ocupantes','5']].map(([label,value])=>({label,value})),featured:true},
  {slug:'jetta-gli',title:'Jetta GLI',subtitle:'Performance que transforma cada trajeto.',intro:'Um sedã esportivo para quem procura performance, tecnologia e acabamento premium.',price:'',availability:'',hero_image:'',gallery:[],features:[['Motor 2.0 TSI','Performance e resposta para uma condução esportiva.'],['Câmbio DSG','Trocas rápidas e precisas.'],['Acabamento premium','Detalhes pensados para uma experiência superior.'],['Tecnologia','Recursos de conectividade e assistência ao motorista.']].map(([title,description])=>({title,description})),specs:[['Motor','2.0 TSI'],['Transmissão','DSG'],['Tração','Dianteira'],['Categoria','Sedã esportivo']].map(([label,value])=>({label,value})),featured:true},
  {slug:'polo',title:'Polo',subtitle:'Tecnologia e personalidade para todos os dias.',intro:'Um hatch Volkswagen que entrega equilíbrio entre dirigibilidade, tecnologia, segurança e praticidade.',price:'',availability:'',hero_image:'',gallery:[],features:[['Dirigibilidade','Acerto que favorece a condução urbana e rodoviária.'],['Tecnologia','Conectividade e recursos modernos.'],['Segurança','Soluções pensadas para proteger você.'],['Praticidade','Um Volkswagen versátil para a rotina.']].map(([title,description])=>({title,description})),specs:[['Categoria','Hatch'],['Motorização','Turbo'],['Transmissão','Automática'],['Ocupantes','5']].map(([label,value])=>({label,value})),featured:true},
  {slug:'tera',title:'Tera',subtitle:'O novo SUV Volkswagen para a sua próxima história.',intro:'Design, tecnologia e versatilidade em um novo SUV Volkswagen pensado para uma nova geração de clientes.',price:'',availability:'',hero_image:'',gallery:[],features:[['Novo design','Uma identidade SUV marcante e contemporânea.'],['Tecnologia','Recursos para conectar você ao seu dia.'],['Versatilidade','Praticidade para diferentes momentos.'],['Volkswagen','Engenharia e experiência em um novo produto.']].map(([title,description])=>({title,description})),specs:[['Categoria','SUV'],['Motorização','Turbo'],['Transmissão','Automática'],['Ocupantes','5']].map(([label,value])=>({label,value})),featured:true}
];
